# pre-commit run --all-files
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-ast
    -   id: check-byte-order-marker
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
        exclude: "resources/.*|docs/make.bat"
    -   id: trailing-whitespace
    -   id: mixed-line-ending
        args: ['--fix=lf']
        exclude: "docs/make.bat"
    -   id: check-added-large-files
        args: ['--maxkb=1000']

-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    -   id: black
        args: [--target-version, py37]

-   repo: https://github.com/asottile/blacken-docs
    rev: 1.18.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==22.1.0]
        exclude: "docs/user/robustness.md"

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.5.3
    hooks:
    -   id: ruff
        args: ['--fix']

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.16.0
    hooks:
    -   id: pyupgrade
        args: [--py38-plus]

-   repo: https://github.com/pycqa/flake8
    rev: 7.1.0
    hooks:
    -   id: flake8
        args: ["--ignore", "E,W,F"]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.10.1'
    hooks:
      - id: mypy
        additional_dependencies: [types-Pillow==10.0.0.2]
        files: ^postbin/.*
